require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssessmentsController do

  # This should return the minimal set of attributes required to create a valid
  # Assessment. As you add validations to Assessment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "assessment_type" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssessmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all assessments as @assessments" do
      assessment = Assessment.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:assessments)).to eq([assessment])
    end
  end

  describe "GET show" do
    it "assigns the requested assessment as @assessment" do
      assessment = Assessment.create! valid_attributes
      get :show, {:id => assessment.to_param}, valid_session
      expect(assigns(:assessment)).to eq(assessment)
    end
  end

  describe "GET new" do
    it "assigns a new assessment as @assessment" do
      get :new, {}, valid_session
      expect(assigns(:assessment)).to be_a_new(Assessment)
    end
  end

  describe "GET edit" do
    it "assigns the requested assessment as @assessment" do
      assessment = Assessment.create! valid_attributes
      get :edit, {:id => assessment.to_param}, valid_session
      expect(assigns(:assessment)).to eq(assessment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Assessment" do
        expect {
          post :create, {:assessment => valid_attributes}, valid_session
        }.to change(Assessment, :count).by(1)
      end

      it "assigns a newly created assessment as @assessment" do
        post :create, {:assessment => valid_attributes}, valid_session
        expect(assigns(:assessment)).to be_a(Assessment)
        expect(assigns(:assessment)).to be_persisted
      end

      it "redirects to the created assessment" do
        post :create, {:assessment => valid_attributes}, valid_session
        expect(response).to redirect_to(Assessment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assessment as @assessment" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Assessment).to receive(:save).and_return(false)
        post :create, {:assessment => { "assessment_type" => "invalid value" }}, valid_session
        expect(assigns(:assessment)).to be_a_new(Assessment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Assessment).to receive(:save).and_return(false)
        post :create, {:assessment => { "assessment_type" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assessment" do
        assessment = Assessment.create! valid_attributes
        # Assuming there are no other assessments in the database, this
        # specifies that the Assessment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Assessment).to receive(:update).with({ "assessment_type" => "" })
        put :update, {:id => assessment.to_param, :assessment => { "assessment_type" => "" }}, valid_session
      end

      it "assigns the requested assessment as @assessment" do
        assessment = Assessment.create! valid_attributes
        put :update, {:id => assessment.to_param, :assessment => valid_attributes}, valid_session
        expect(assigns(:assessment)).to eq(assessment)
      end

      it "redirects to the assessment" do
        assessment = Assessment.create! valid_attributes
        put :update, {:id => assessment.to_param, :assessment => valid_attributes}, valid_session
        expect(response).to redirect_to(assessment)
      end
    end

    describe "with invalid params" do
      it "assigns the assessment as @assessment" do
        assessment = Assessment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Assessment).to receive(:save).and_return(false)
        put :update, {:id => assessment.to_param, :assessment => { "assessment_type" => "invalid value" }}, valid_session
        expect(assigns(:assessment)).to eq(assessment)
      end

      it "re-renders the 'edit' template" do
        assessment = Assessment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Assessment).to receive(:save).and_return(false)
        put :update, {:id => assessment.to_param, :assessment => { "assessment_type" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assessment" do
      assessment = Assessment.create! valid_attributes
      expect {
        delete :destroy, {:id => assessment.to_param}, valid_session
      }.to change(Assessment, :count).by(-1)
    end

    it "redirects to the assessments list" do
      assessment = Assessment.create! valid_attributes
      delete :destroy, {:id => assessment.to_param}, valid_session
      expect(response).to redirect_to(assessments_url)
    end
  end

end
